export const captureException = (err: string, hint: string = 'err'): void => {
  console.log(err, hint)
}
