export const captureException = (err: string, hint: string = 'err') => {
  console.log(err, hint)
}
